2021-04-22 08:55:28,368 INFO    MainThread:1189333 [internal.py:wandb_internal():88] W&B internal server running at pid: 1189333, started at: 2021-04-22 08:55:28.367915
2021-04-22 08:55:28,370 DEBUG   HandlerThread:1189333 [handler.py:handle_request():101] handle_request: check_version
2021-04-22 08:55:28,371 DEBUG   SenderThread:1189333 [sender.py:send():122] send: header
2021-04-22 08:55:28,371 INFO    WriterThread:1189333 [datastore.py:open_for_write():77] open: /home/ubuntu/evgeny/GEP-forecasts/EVERGI/wandb/run-20210422_085527-22c4lhym/run-22c4lhym.wandb
2021-04-22 08:55:28,372 DEBUG   SenderThread:1189333 [sender.py:send():122] send: request
2021-04-22 08:55:28,372 DEBUG   SenderThread:1189333 [sender.py:send_request():131] send_request: check_version
2021-04-22 08:55:28,504 DEBUG   SenderThread:1189333 [sender.py:send():122] send: run
2021-04-22 08:55:28,626 WARNING MainThread:1189333 [internal.py:wandb_internal():146] Internal process interrupt: 1
2021-04-22 08:55:28,761 INFO    SenderThread:1189333 [sender.py:_start_run_threads():596] run started: 22c4lhym with start time 1619081727
2021-04-22 08:55:46,390 WARNING MainThread:1189333 [internal.py:wandb_internal():146] Internal process interrupt: 2
2021-04-22 08:55:46,390 ERROR   MainThread:1189333 [internal.py:wandb_internal():149] Internal process interrupted.
2021-04-22 08:55:46,508 INFO    WriterThread:1189333 [datastore.py:close():258] close: /home/ubuntu/evgeny/GEP-forecasts/EVERGI/wandb/run-20210422_085527-22c4lhym/run-22c4lhym.wandb
2021-04-22 08:55:46,526 INFO    HandlerThread:1189333 [handler.py:finish():532] shutting down handler
2021-04-22 08:55:46,766 INFO    SenderThread:1189333 [sender.py:finish():814] shutting down sender
2021-04-22 08:55:49,015 INFO    MainThread:1189333 [internal.py:handle_exit():78] Internal process exited
